export const teamStatKeys: TeamStatKey[] = [
  { label: "우리 팀 득점", key: "match_team_stats_our_score" },
  { label: "상대 팀 득점", key: "match_team_stats_other_score" },
  { label: "점유율", key: "match_team_stats_possession" },
  { label: "총 슈팅", key: "match_team_stats_total_shot" },
  { label: "기대 득점", key: "match_team_stats_expected_goal" },
  { label: "총 패스", key: "match_team_stats_total_pass" },
  { label: "총 태클", key: "match_team_stats_total_tackle" },
  { label: "성공적인 태클", key: "match_team_stats_success_tackle" },
  { label: "선방", key: "match_team_stats_saved" },
  { label: "코너킥", key: "match_team_stats_cornerkick" },
  { label: "프리킥", key: "match_team_stats_freekick" },
  { label: "페널티킥", key: "match_team_stats_penaltykick" },
  { label: "MOM 선수", key: "mom_player_nickname" },
];
