export const formations = [
  [
    { position: "ST", top: "10%", left: "50%" },
    { position: "LW", top: "20%", left: "30%" },
    { position: "RW", top: "20%", left: "70%" },
    { position: "LCM", top: "40%", left: "30%" },
    { position: "CM", top: "40%", left: "50%" },
    { position: "RCM", top: "40%", left: "70%" },
    { position: "LB", top: "60%", left: "20%" },
    { position: "LCB", top: "60%", left: "40%" },
    { position: "RCB", top: "60%", left: "60%" },
    { position: "RB", top: "60%", left: "80%" },
    { position: "GK", top: "80%", left: "50%" },
  ],
  [
    { position: "ST", top: "10%", left: "40%" },
    { position: "ST", top: "10%", left: "60%" },
    { position: "LM", top: "30%", left: "20%" },
    { position: "LCM", top: "30%", left: "40%" },
    { position: "RCM", top: "30%", left: "60%" },
    { position: "RM", top: "30%", left: "80%" },
    { position: "LB", top: "50%", left: "20%" },
    { position: "LCB", top: "50%", left: "40%" },
    { position: "RCB", top: "50%", left: "60%" },
    { position: "RB", top: "50%", left: "80%" },
    { position: "GK", top: "70%", left: "50%" },
  ],
  [
    { position: "ST", top: "10%", left: "50%" },
    { position: "CAM", top: "30%", left: "50%" },
    { position: "LM", top: "30%", left: "30%" },
    { position: "RM", top: "30%", left: "70%" },
    { position: "LCM", top: "50%", left: "40%" },
    { position: "RCM", top: "50%", left: "60%" },
    { position: "LB", top: "70%", left: "20%" },
    { position: "LCB", top: "70%", left: "40%" },
    { position: "RCB", top: "70%", left: "60%" },
    { position: "RB", top: "70%", left: "80%" },
    { position: "GK", top: "90%", left: "50%" },
  ],
  [
    { position: "ST", top: "10%", left: "50%" },
    { position: "LW", top: "20%", left: "30%" },
    { position: "RW", top: "20%", left: "70%" },
    { position: "LCM", top: "40%", left: "30%" },
    { position: "CM", top: "40%", left: "50%" },
    { position: "RCM", top: "40%", left: "70%" },
    { position: "LM", top: "60%", left: "20%" },
    { position: "RM", top: "60%", left: "80%" },
    { position: "LCB", top: "80%", left: "30%" },
    { position: "CB", top: "80%", left: "50%" },
    { position: "RCB", top: "80%", left: "70%" },
    { position: "GK", top: "90%", left: "50%" },
  ],
  [
    { position: "ST", top: "10%", left: "50%" },
    { position: "LW", top: "20%", left: "30%" },
    { position: "RW", top: "20%", left: "70%" },
    { position: "LCM", top: "40%", left: "30%" },
    { position: "CM", top: "40%", left: "50%" },
    { position: "RCM", top: "40%", left: "70%" },
    { position: "LM", top: "60%", left: "20%" },
    { position: "RM", top: "60%", left: "80%" },
    { position: "LCB", top: "80%", left: "30%" },
    { position: "CB", top: "80%", left: "50%" },
    { position: "RCB", top: "80%", left: "70%" },
    { position: "GK", top: "90%", left: "50%" },
  ],
];
