export const formationCoordinateMap = {
  "4-4-2": [
    { position: "GK", top: "85%", left: "50%" },
    { position: "RB", top: "65%", left: "15%" },
    { position: "RCB", top: "65%", left: "35%" },
    { position: "LCB", top: "65%", left: "65%" },
    { position: "LB", top: "65%", left: "85%" },
    { position: "RM", top: "50%", left: "15%" },
    { position: "RCM", top: "50%", left: "35%" },
    { position: "LCM", top: "50%", left: "65%" },
    { position: "LM", top: "50%", left: "85%" },
    { position: "ST", top: "30%", left: "40%" },
    { position: "ST", top: "30%", left: "60%" },
  ],
  "4-3-3": [
    { position: "GK", top: "85%", left: "50%" },
    { position: "RB", top: "65%", left: "15%" },
    { position: "RCB", top: "65%", left: "35%" },
    { position: "LCB", top: "65%", left: "65%" },
    { position: "LB", top: "65%", left: "85%" },
    { position: "RCM", top: "50%", left: "30%" },
    { position: "CM", top: "50%", left: "50%" },
    { position: "LCM", top: "50%", left: "70%" },
    { position: "RW", top: "30%", left: "25%" },
    { position: "ST", top: "25%", left: "50%" },
    { position: "LW", top: "30%", left: "75%" },
  ],
  "3-5-2": [
    { position: "GK", top: "85%", left: "50%" },
    { position: "RCB", top: "65%", left: "30%" },
    { position: "CB", top: "65%", left: "50%" },
    { position: "LCB", top: "65%", left: "70%" },
    { position: "RM", top: "50%", left: "15%" },
    { position: "RCM", top: "50%", left: "35%" },
    { position: "CM", top: "50%", left: "50%" },
    { position: "LCM", top: "50%", left: "65%" },
    { position: "LM", top: "50%", left: "85%" },
    { position: "ST", top: "30%", left: "40%" },
    { position: "ST", top: "30%", left: "60%" },
  ],
  "3-4-3": [
    { position: "GK", top: "85%", left: "50%" },
    { position: "RCB", top: "65%", left: "30%" },
    { position: "CB", top: "65%", left: "50%" },
    { position: "LCB", top: "65%", left: "70%" },
    { position: "RM", top: "50%", left: "20%" },
    { position: "RCM", top: "50%", left: "40%" },
    { position: "LCM", top: "50%", left: "60%" },
    { position: "LM", top: "50%", left: "80%" },
    { position: "RW", top: "30%", left: "25%" },
    { position: "ST", top: "25%", left: "50%" },
    { position: "LW", top: "30%", left: "75%" },
  ],
  "5-3-2": [
    { position: "GK", top: "85%", left: "50%" },
    { position: "RWB", top: "65%", left: "10%" },
    { position: "RCB", top: "65%", left: "30%" },
    { position: "CB", top: "65%", left: "50%" },
    { position: "LCB", top: "65%", left: "70%" },
    { position: "LWB", top: "65%", left: "90%" },
    { position: "RCM", top: "50%", left: "35%" },
    { position: "CM", top: "50%", left: "50%" },
    { position: "LCM", top: "50%", left: "65%" },
    { position: "ST", top: "30%", left: "40%" },
    { position: "ST", top: "30%", left: "60%" },
  ],
  "5-4-1": [
    { position: "GK", top: "85%", left: "50%" },
    { position: "RWB", top: "65%", left: "10%" },
    { position: "RCB", top: "65%", left: "30%" },
    { position: "CB", top: "65%", left: "50%" },
    { position: "LCB", top: "65%", left: "70%" },
    { position: "LWB", top: "65%", left: "90%" },
    { position: "RM", top: "50%", left: "15%" },
    { position: "RCM", top: "50%", left: "35%" },
    { position: "LCM", top: "50%", left: "65%" },
    { position: "LM", top: "50%", left: "85%" },
    { position: "ST", top: "30%", left: "50%" },
  ],
};
